services:
  telegram_agent:
    build: .
    container_name: telegram_ai_agent
    restart: always
    env_file:
      - .env
    volumes:
      - ./agent_database.sqlite:/app/agent_database.sqlite
      - ./telegram_ai_agent.session:/app/telegram_ai_agent.session
